apiVersion: batch/v1
kind: Job
metadata:
  name: test-dns
spec:
  template:
    spec:
      containers:
      - name: test-dns
        image: andreatp/test-dns:0.0.1
        args: ['cloudflow-strimzi-kafka-0.cloudflow-strimzi-kafka-brokers.cloudflow.svc', '9092']
      restartPolicy: Never
